version: "3.8"

services:
  mirth-connect:
    image: nextgenhealthcare/connect:latest
    container_name: mirth-connect
    env_file:
      - .env
    ports:
      - "8080:8080/tcp"
      - "8443:8443/tcp"
    depends_on:
      - db
    networks:
      - default
    volumes:
      - ./extensions:/opt/connect/custom-extensions

  db:
    image: postgres
    container_name: mirth-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - default

networks:
  default:
    